export const DEFAULT_REPORT_STATE = {
  patient: {
    name: "",
    age: "",
    sex: "Male",
    uhid: "",
    date: new Date().toISOString().substring(0, 10),
    referringDoctor: "",
    opdIpd: "OPD",
    wardBed: "",
    indication: "Chest pain",
  },
  echocardiographer: "Dr V D Tripathi, DM Cardiology",
  measurements: {
    ivsd: "",
    lvidd: "",
    lvids: "",
    lvpwd: "",
    laSize: "",
    aorticRoot: "",
    ef: "",
    fs: "",
    lvMass: "",
    tapse: "",
    rvspPasp: "",
    ivcDiameter: "",
    eaRatio: "",
    eePrime: "",
    decelTime: "",
    lvotVti: "",
    avPeakGradient: "",
    avMeanGradient: "",
    mvGradient: "",
    trVelocity: "",
  },
  lv: {
    size: "Normal",
    systolic: "Normal",
    rwma: "Absent",
    rwmaTerritory: "None",
    lvh: "None",
    diastolic: "Normal",
  },
  rv: {
    size: "Normal",
    function: "Normal",
  },
  laRa: {
    laSize: "Normal",
    raSize: "Normal",
  },
  ias: "Intact",
  valves: {
    mitral: { morphology: "Normal", stenosis: "None", regurgitation: "None", remarks: "" },
    aortic: { morphology: "Normal", stenosis: "None", regurgitation: "None", remarks: "" },
    tricuspid: { morphology: "Normal", stenosis: "None", regurgitation: "None", remarks: "" },
    pulmonary: { morphology: "Normal", stenosis: "None", regurgitation: "None", remarks: "" },
  },
  doppler: {
    trJet: "Absent",
    paspSeverity: "Normal",
    ivc: "Normal collapsible",
  },
  pericardium: {
    effusion: "None",
  },
  aorta: {
    root: "Normal",
    ascending: "Normal",
  },
  masses: {
    clotVegMass: "Absent",
  },
  finalImpression: "",
  advice: "",
};

export const TEMPLATES = {
  normal: {
    name: "Normal adult echo",
    data: {
      measurements: {
        ivsd: "9",
        lvidd: "46",
        lvids: "30",
        lvpwd: "9",
        laSize: "32",
        aorticRoot: "30",
        ef: "64",
        fs: "35",
        lvMass: "115",
        tapse: "22",
        rvspPasp: "25",
        ivcDiameter: "15",
        eaRatio: "1.2",
        eePrime: "7",
        decelTime: "180",
        lvotVti: "20",
        avPeakGradient: "6",
        avMeanGradient: "3",
        mvGradient: "",
        trVelocity: "2.1",
      },
      lv: {
        size: "Normal",
        systolic: "Normal",
        rwma: "Absent",
        rwmaTerritory: "None",
        lvh: "None",
        diastolic: "Normal",
      },
      rv: { size: "Normal", function: "Normal" },
      laRa: { laSize: "Normal", raSize: "Normal" },
      ias: "Intact",
      valves: {
        mitral: { morphology: "Normal", stenosis: "None", regurgitation: "None", remarks: "Normal valves" },
        aortic: { morphology: "Normal", stenosis: "None", regurgitation: "None", remarks: "Normal valves" },
        tricuspid: { morphology: "Normal", stenosis: "None", regurgitation: "None", remarks: "Normal valves" },
        pulmonary: { morphology: "Normal", stenosis: "None", regurgitation: "None", remarks: "Normal valves" },
      },
      doppler: { trJet: "Absent", paspSeverity: "Normal", ivc: "Normal collapsible" },
      pericardium: { effusion: "None" },
      aorta: { root: "Normal", ascending: "Normal" },
      masses: { clotVegMass: "Absent" },
      finalImpression: "Normal study with normal chambers and normal biventricular systolic function. EF 64%. No valvular stenosis/regurgitation. No pericardial effusion.",
      advice: "Clinical correlation.",
    },
  },
  cad: {
    name: "CAD with LV dysfunction",
    data: {
      measurements: {
        ivsd: "10",
        lvidd: "54",
        lvids: "42",
        lvpwd: "9",
        laSize: "36",
        aorticRoot: "32",
        ef: "40",
        fs: "22",
        lvMass: "165",
        tapse: "18",
        rvspPasp: "30",
        ivcDiameter: "17",
        eaRatio: "0.7",
        eePrime: "12",
        decelTime: "240",
        lvotVti: "15",
        avPeakGradient: "6",
        avMeanGradient: "3",
        mvGradient: "",
        trVelocity: "2.4",
      },
      lv: {
        size: "Dilated",
        systolic: "Moderate LV dysfunction",
        rwma: "Present",
        rwmaTerritory: "LAD",
        lvh: "None",
        diastolic: "Grade I",
      },
      rv: { size: "Normal", function: "Normal" },
      laRa: { laSize: "Mildly dilated", raSize: "Normal" },
      ias: "Intact",
      valves: {
        mitral: { morphology: "Normal", stenosis: "None", regurgitation: "Mild", remarks: "Mild functional MR" },
        aortic: { morphology: "Normal", stenosis: "None", regurgitation: "None", remarks: "" },
        tricuspid: { morphology: "Normal", stenosis: "None", regurgitation: "None", remarks: "" },
        pulmonary: { morphology: "Normal", stenosis: "None", regurgitation: "None", remarks: "" },
      },
      doppler: { trJet: "Present", paspSeverity: "Normal", ivc: "Normal collapsible" },
      pericardium: { effusion: "None" },
      aorta: { root: "Normal", ascending: "Normal" },
      masses: { clotVegMass: "Absent" },
      finalImpression: "Dilated LV with moderate LV systolic function (EF 40%). Regional wall motion abnormality (RWMA) present in LAD territory. Grade I diastolic dysfunction. Mild functional MR.",
      advice: "Correlate with ECG and clinical profile.",
    },
  },
  post_mi_rwma: {
    name: "Post MI RWMA",
    data: {
      measurements: {
        ivsd: "8",
        lvidd: "56",
        lvids: "45",
        lvpwd: "10",
        laSize: "38",
        aorticRoot: "31",
        ef: "35",
        fs: "19",
        lvMass: "180",
        tapse: "16",
        rvspPasp: "35",
        ivcDiameter: "18",
        eaRatio: "0.6",
        eePrime: "14",
        decelTime: "260",
        lvotVti: "13",
        avPeakGradient: "5",
        avMeanGradient: "3",
        mvGradient: "",
        trVelocity: "2.6",
      },
      lv: {
        size: "Dilated",
        systolic: "Moderate LV dysfunction",
        rwma: "Present",
        rwmaTerritory: "RCA",
        lvh: "None",
        diastolic: "Grade I",
      },
      rv: { size: "Normal", function: "Normal" },
      laRa: { laSize: "Mildly dilated", raSize: "Normal" },
      ias: "Intact",
      valves: {
        mitral: { morphology: "Normal", stenosis: "None", regurgitation: "Mild", remarks: "Mild functional MR due to tethering" },
        aortic: { morphology: "Normal", stenosis: "None", regurgitation: "None", remarks: "" },
        tricuspid: { morphology: "Normal", stenosis: "None", regurgitation: "Mild", remarks: "Trivial TR" },
        pulmonary: { morphology: "Normal", stenosis: "None", regurgitation: "None", remarks: "" },
      },
      doppler: { trJet: "Present", paspSeverity: "Mild PH", ivc: "Normal collapsible" },
      pericardium: { effusion: "None" },
      aorta: { root: "Normal", ascending: "Normal" },
      masses: { clotVegMass: "Absent" },
      finalImpression: "Post-MI status. Dilated LV with moderate biventricular/LV systolic dysfunction (EF 35%). RWMA present in RCA (inferior wall) territory. Grade I diastolic dysfunction. Mild MR, mild TR with mild pulmonary hypertension.",
      advice: "Medical management as advised. Serial follow up echo.",
    },
  },
  hfref: {
    name: "HFrEF",
    data: {
      measurements: {
        ivsd: "9",
        lvidd: "65",
        lvids: "56",
        lvpwd: "9",
        laSize: "44",
        aorticRoot: "32",
        ef: "24",
        fs: "13",
        lvMass: "220",
        tapse: "13",
        rvspPasp: "45",
        ivcDiameter: "22",
        eaRatio: "2.4",
        eePrime: "18",
        decelTime: "120",
        lvotVti: "10",
        avPeakGradient: "4",
        avMeanGradient: "2",
        mvGradient: "",
        trVelocity: "3.1",
      },
      lv: {
        size: "Dilated",
        systolic: "Severe LV dysfunction",
        rwma: "Present",
        rwmaTerritory: "Global hypokinesia",
        lvh: "None",
        diastolic: "Grade III",
      },
      rv: { size: "Dilated", function: "Moderately reduced" },
      laRa: { laSize: "Severely dilated", raSize: "Dilated" },
      ias: "Intact",
      valves: {
        mitral: { morphology: "Normal", stenosis: "None", regurgitation: "Moderate", remarks: "Moderate functional MR" },
        aortic: { morphology: "Normal", stenosis: "None", regurgitation: "None", remarks: "" },
        tricuspid: { morphology: "Normal", stenosis: "None", regurgitation: "Moderate", remarks: "Moderate functional TR" },
        pulmonary: { morphology: "Normal", stenosis: "None", regurgitation: "None", remarks: "" },
      },
      doppler: { trJet: "Present", paspSeverity: "Moderate PH", ivc: "Dilated with poor collapse" },
      pericardium: { effusion: "Minimal" },
      aorta: { root: "Normal", ascending: "Normal" },
      masses: { clotVegMass: "Absent" },
      finalImpression: "Heart Failure with reduced Ejection Fraction (HFrEF). Severely dilated LV with global hypokinesia and severe LV systolic dysfunction (EF 24%). Moderately reduced RV function. Grade III (restrictive pattern) diastolic dysfunction. Moderate MR, moderate TR, and moderate pulmonary hypertension. Dilated IVC with poor collapse.",
      advice: "Guideline-directed medical therapy (GDMT) optimization.",
    },
  },
  hfpef: {
    name: "HFpEF",
    data: {
      measurements: {
        ivsd: "12",
        lvidd: "45",
        lvids: "28",
        lvpwd: "12",
        laSize: "41",
        aorticRoot: "33",
        ef: "60",
        fs: "37",
        lvMass: "155",
        tapse: "21",
        rvspPasp: "38",
        ivcDiameter: "19",
        eaRatio: "0.6",
        eePrime: "15",
        decelTime: "250",
        lvotVti: "19",
        avPeakGradient: "8",
        avMeanGradient: "4",
        mvGradient: "",
        trVelocity: "2.8",
      },
      lv: {
        size: "Normal",
        systolic: "Normal",
        rwma: "Absent",
        rwmaTerritory: "None",
        lvh: "Concentric LVH",
        diastolic: "Grade II",
      },
      rv: { size: "Normal", function: "Normal" },
      laRa: { laSize: "Moderately dilated", raSize: "Normal" },
      ias: "Intact",
      valves: {
        mitral: { morphology: "Thickened", stenosis: "None", regurgitation: "Mild", remarks: "Mild MAC (mitral annular calcification)" },
        aortic: { morphology: "Calcified", stenosis: "None", regurgitation: "None", remarks: "Aortic sclerosis" },
        tricuspid: { morphology: "Normal", stenosis: "None", regurgitation: "Mild", remarks: "Mild TR" },
        pulmonary: { morphology: "Normal", stenosis: "None", regurgitation: "None", remarks: "" },
      },
      doppler: { trJet: "Present", paspSeverity: "Mild PH", ivc: "Normal collapsible" },
      pericardium: { effusion: "None" },
      aorta: { root: "Normal", ascending: "Normal" },
      masses: { clotVegMass: "Absent" },
      finalImpression: "Heart Failure with preserved Ejection Fraction (HFpEF). Concentric LVH with normal LV systolic function (EF 60%). Grade II diastolic dysfunction with elevated LV filling pressures (E/e' 15). Moderately dilated LA. Mild TR with mild pulmonary hypertension.",
      advice: "Control hypertension and optimize diuretics.",
    },
  },
  rheumatic_ms: {
    name: "Rheumatic mitral stenosis",
    data: {
      measurements: {
        ivsd: "9",
        lvidd: "42",
        lvids: "27",
        lvpwd: "9",
        laSize: "50",
        aorticRoot: "28",
        ef: "60",
        fs: "35",
        lvMass: "105",
        tapse: "17",
        rvspPasp: "55",
        ivcDiameter: "20",
        eaRatio: "",
        eePrime: "",
        decelTime: "310",
        lvotVti: "15",
        avPeakGradient: "6",
        avMeanGradient: "3",
        mvGradient: "12",
        trVelocity: "3.5",
      },
      lv: {
        size: "Normal",
        systolic: "Normal",
        rwma: "Absent",
        rwmaTerritory: "None",
        lvh: "None",
        diastolic: "Indeterminate",
      },
      rv: { size: "Dilated", function: "Normal" },
      laRa: { laSize: "Severely dilated", raSize: "Dilated" },
      ias: "Intact",
      valves: {
        mitral: { morphology: "Rheumatic", stenosis: "Severe", regurgitation: "Mild", remarks: "Mitral valve thickened, calcified with hockey-stick deformity of anterior mitral leaflet, restricted PML movement. Planimetered MVA is 1.0 cm2." },
        aortic: { morphology: "Thickened", stenosis: "None", regurgitation: "Mild", remarks: "Mild AR" },
        tricuspid: { morphology: "Normal", stenosis: "None", regurgitation: "Moderate", remarks: "Moderate TR (secondary)" },
        pulmonary: { morphology: "Normal", stenosis: "None", regurgitation: "None", remarks: "" },
      },
      doppler: { trJet: "Present", paspSeverity: "Severe PH", ivc: "Normal collapsible" },
      pericardium: { effusion: "None" },
      aorta: { root: "Normal", ascending: "Normal" },
      masses: { clotVegMass: "Absent" },
      finalImpression: "Severe Rheumatic Mitral Stenosis (MVA ~ 1.0 cm2, mean MV gradient 12 mmHg). Severely dilated LA. Mild AR, moderate TR. Severe pulmonary hypertension (PASP 55 mmHg). Normal biventricular systolic function (EF 60%).",
      advice: "Consider Balloon Mitral Valvuloplasty (BMV) / Surgical consult.",
    },
  },
  aortic_stenosis: {
    name: "Aortic stenosis",
    data: {
      measurements: {
        ivsd: "14",
        lvidd: "44",
        lvids: "28",
        lvpwd: "14",
        laSize: "40",
        aorticRoot: "32",
        ef: "60",
        fs: "36",
        lvMass: "190",
        tapse: "20",
        rvspPasp: "35",
        ivcDiameter: "16",
        eaRatio: "0.6",
        eePrime: "14",
        decelTime: "240",
        lvotVti: "15",
        avPeakGradient: "75",
        avMeanGradient: "45",
        mvGradient: "",
        trVelocity: "2.6",
      },
      lv: {
        size: "Normal",
        systolic: "Normal",
        rwma: "Absent",
        rwmaTerritory: "None",
        lvh: "Concentric LVH",
        diastolic: "Grade I",
      },
      rv: { size: "Normal", function: "Normal" },
      laRa: { laSize: "Mildly dilated", raSize: "Normal" },
      ias: "Intact",
      valves: {
        mitral: { morphology: "Normal", stenosis: "None", regurgitation: "Mild", remarks: "" },
        aortic: { morphology: "Calcified", stenosis: "Severe", regurgitation: "None", remarks: "Calcified trileaflet aortic valve with restricted opening. Peak velocity across AV is 4.3 m/s." },
        tricuspid: { morphology: "Normal", stenosis: "None", regurgitation: "None", remarks: "" },
        pulmonary: { morphology: "Normal", stenosis: "None", regurgitation: "None", remarks: "" },
      },
      doppler: { trJet: "Present", paspSeverity: "Mild PH", ivc: "Normal collapsible" },
      pericardium: { effusion: "None" },
      aorta: { root: "Normal", ascending: "Normal" },
      masses: { clotVegMass: "Absent" },
      finalImpression: "Severe Aortic Stenosis (Peak gradient 75 mmHg, Mean gradient 45 mmHg, Peak velocity 4.3 m/s). Concentric LVH with normal biventricular systolic function (EF 60%). Mild MR. Grade I diastolic dysfunction.",
      advice: "Refer to Cardiology / Cardiothoracic surgery for AVR consideration.",
    },
  },
  aortic_regurgitation: {
    name: "Aortic regurgitation",
    data: {
      measurements: {
        ivsd: "10",
        lvidd: "62",
        lvids: "44",
        lvpwd: "10",
        laSize: "39",
        aorticRoot: "41",
        ef: "52",
        fs: "29",
        lvMass: "198",
        tapse: "19",
        rvspPasp: "32",
        ivcDiameter: "17",
        eaRatio: "1.1",
        eePrime: "10",
        decelTime: "190",
        lvotVti: "22",
        avPeakGradient: "10",
        avMeanGradient: "5",
        mvGradient: "",
        trVelocity: "2.5",
      },
      lv: {
        size: "Dilated",
        systolic: "Mild LV dysfunction",
        rwma: "Absent",
        rwmaTerritory: "None",
        lvh: "Eccentric LVH",
        diastolic: "Grade I",
      },
      rv: { size: "Normal", function: "Normal" },
      laRa: { laSize: "Mildly dilated", raSize: "Normal" },
      ias: "Intact",
      valves: {
        mitral: { morphology: "Normal", stenosis: "None", regurgitation: "None", remarks: "" },
        aortic: { morphology: "Thickened", stenosis: "None", regurgitation: "Severe", remarks: "Aortic valve leaflets are thickened with poor coaptation. Jet width/LVOT ratio > 65%, steep AR deceleration slope." },
        tricuspid: { morphology: "Normal", stenosis: "None", regurgitation: "None", remarks: "" },
        pulmonary: { morphology: "Normal", stenosis: "None", regurgitation: "None", remarks: "" },
      },
      doppler: { trJet: "Present", paspSeverity: "Normal", ivc: "Normal collapsible" },
      pericardium: { effusion: "None" },
      aorta: { root: "Dilated", ascending: "Dilated" },
      masses: { clotVegMass: "Absent" },
      finalImpression: "Severe Aortic Regurgitation (AR). Dilated LV with eccentric LVH, mild LV systolic dysfunction (EF 52%). Dilated aortic root and ascending aorta. Normal RV size and function.",
      advice: "Clinical correlation, surveillance vs valve surgery evaluation.",
    },
  },
  dilated_cardiomyopathy: {
    name: "Dilated cardiomyopathy",
    data: {
      measurements: {
        ivsd: "8",
        lvidd: "68",
        lvids: "60",
        lvpwd: "8",
        laSize: "46",
        aorticRoot: "30",
        ef: "20",
        fs: "12",
        lvMass: "235",
        tapse: "12",
        rvspPasp: "48",
        ivcDiameter: "23",
        eaRatio: "2.5",
        eePrime: "20",
        decelTime: "110",
        lvotVti: "9",
        avPeakGradient: "4",
        avMeanGradient: "2",
        mvGradient: "",
        trVelocity: "3.2",
      },
      lv: {
        size: "Dilated",
        systolic: "Severe LV dysfunction",
        rwma: "Present",
        rwmaTerritory: "Global hypokinesia",
        lvh: "None",
        diastolic: "Grade III",
      },
      rv: { size: "Dilated", function: "Severely reduced" },
      laRa: { laSize: "Severely dilated", raSize: "Dilated" },
      ias: "Intact",
      valves: {
        mitral: { morphology: "Normal", stenosis: "None", regurgitation: "Moderate", remarks: "Functional MR due to annular dilation" },
        aortic: { morphology: "Normal", stenosis: "None", regurgitation: "None", remarks: "" },
        tricuspid: { morphology: "Normal", stenosis: "None", regurgitation: "Moderate", remarks: "Functional TR" },
        pulmonary: { morphology: "Normal", stenosis: "None", regurgitation: "None", remarks: "" },
      },
      doppler: { trJet: "Present", paspSeverity: "Moderate PH", ivc: "Dilated with poor collapse" },
      pericardium: { effusion: "Minimal" },
      aorta: { root: "Normal", ascending: "Normal" },
      masses: { clotVegMass: "Absent" },
      finalImpression: "Dilated Cardiomyopathy (DCM). Severe bi-chamber dilation, global hypokinesia and severe biventricular systolic dysfunction (EF 20%). Grade III (restrictive) diastolic dysfunction. Moderate functional MR and TR. Moderate pulmonary hypertension. Dilated non-collapsible IVC.",
      advice: "Urgent heart failure management, consideration for ICD/CRT device therapy.",
    },
  },
  hypertensive_heart_disease: {
    name: "Hypertensive heart disease",
    data: {
      measurements: {
        ivsd: "13",
        lvidd: "47",
        lvids: "29",
        lvpwd: "13",
        laSize: "42",
        aorticRoot: "34",
        ef: "62",
        fs: "38",
        lvMass: "172",
        tapse: "22",
        rvspPasp: "32",
        ivcDiameter: "16",
        eaRatio: "0.5",
        eePrime: "13",
        decelTime: "260",
        lvotVti: "21",
        avPeakGradient: "8",
        avMeanGradient: "4",
        mvGradient: "",
        trVelocity: "2.5",
      },
      lv: {
        size: "Normal",
        systolic: "Normal",
        rwma: "Absent",
        rwmaTerritory: "None",
        lvh: "Concentric LVH",
        diastolic: "Grade I",
      },
      rv: { size: "Normal", function: "Normal" },
      laRa: { laSize: "Moderately dilated", raSize: "Normal" },
      ias: "Intact",
      valves: {
        mitral: { morphology: "Thickened", stenosis: "None", regurgitation: "Mild", remarks: "Mild MAC" },
        aortic: { morphology: "Thickened", stenosis: "None", regurgitation: "None", remarks: "Aortic sclerosis" },
        tricuspid: { morphology: "Normal", stenosis: "None", regurgitation: "None", remarks: "" },
        pulmonary: { morphology: "Normal", stenosis: "None", regurgitation: "None", remarks: "" },
      },
      doppler: { trJet: "Present", paspSeverity: "Normal", ivc: "Normal collapsible" },
      pericardium: { effusion: "None" },
      aorta: { root: "Normal", ascending: "Normal" },
      masses: { clotVegMass: "Absent" },
      finalImpression: "Hypertensive Heart Disease. Concentric LVH, normal LV systolic function (EF 62%). Grade I diastolic dysfunction (impaired relaxation). Moderately dilated LA. Aortic sclerosis and mild MAC.",
      advice: "Strict blood pressure control. Repeat echo after 1 year.",
    },
  },
  pulmonary_hypertension: {
    name: "Pulmonary hypertension",
    data: {
      measurements: {
        ivsd: "9",
        lvidd: "44",
        lvids: "28",
        lvpwd: "9",
        laSize: "32",
        aorticRoot: "30",
        ef: "60",
        fs: "36",
        lvMass: "110",
        tapse: "15",
        rvspPasp: "65",
        ivcDiameter: "22",
        eaRatio: "1.1",
        eePrime: "9",
        decelTime: "185",
        lvotVti: "19",
        avPeakGradient: "6",
        avMeanGradient: "3",
        mvGradient: "",
        trVelocity: "4.0",
      },
      lv: {
        size: "Normal",
        systolic: "Normal",
        rwma: "Absent",
        rwmaTerritory: "None",
        lvh: "None",
        diastolic: "Normal",
      },
      rv: { size: "Dilated", function: "Mildly reduced" },
      laRa: { laSize: "Normal", raSize: "Dilated" },
      ias: "Intact",
      valves: {
        mitral: { morphology: "Normal", stenosis: "None", regurgitation: "None", remarks: "" },
        aortic: { morphology: "Normal", stenosis: "None", regurgitation: "None", remarks: "" },
        tricuspid: { morphology: "Normal", stenosis: "None", regurgitation: "Severe", remarks: "Severe TR (secondary to high PA pressure). Flattening of IVS during systole." },
        pulmonary: { morphology: "Normal", stenosis: "None", regurgitation: "Mild", remarks: "Mild PR" },
      },
      doppler: { trJet: "Present", paspSeverity: "Severe PH", ivc: "Dilated with poor collapse" },
      pericardium: { effusion: "Minimal" },
      aorta: { root: "Normal", ascending: "Normal" },
      masses: { clotVegMass: "Absent" },
      finalImpression: "Severe Pulmonary Hypertension (PASP 65 mmHg). Dilated RV with mildly reduced RV systolic function (TAPSE 15mm). Dilated RA. Severe TR and mild PR. IVS flattening suggesting RV pressure overload. Dilated non-collapsible IVC.",
      advice: "Workup for etiology of PAH (Pulmonary Arterial Hypertension).",
    },
  },
  pericardial_effusion: {
    name: "Pericardial effusion",
    data: {
      measurements: {
        ivsd: "9",
        lvidd: "46",
        lvids: "29",
        lvpwd: "9",
        laSize: "32",
        aorticRoot: "30",
        ef: "62",
        fs: "37",
        lvMass: "115",
        tapse: "22",
        rvspPasp: "22",
        ivcDiameter: "22",
        eaRatio: "1.3",
        eePrime: "7",
        decelTime: "170",
        lvotVti: "20",
        avPeakGradient: "6",
        avMeanGradient: "3",
        mvGradient: "",
        trVelocity: "2.0",
      },
      lv: {
        size: "Normal",
        systolic: "Normal",
        rwma: "Absent",
        rwmaTerritory: "None",
        lvh: "None",
        diastolic: "Normal",
      },
      rv: { size: "Normal", function: "Normal" },
      laRa: { laSize: "Normal", raSize: "Normal" },
      ias: "Intact",
      valves: {
        mitral: { morphology: "Normal", stenosis: "None", regurgitation: "None", remarks: "" },
        aortic: { morphology: "Normal", stenosis: "None", regurgitation: "None", remarks: "" },
        tricuspid: { morphology: "Normal", stenosis: "None", regurgitation: "None", remarks: "" },
        pulmonary: { morphology: "Normal", stenosis: "None", regurgitation: "None", remarks: "" },
      },
      doppler: { trJet: "Absent", paspSeverity: "Normal", ivc: "Dilated with poor collapse" },
      pericardium: { effusion: "Large" },
      aorta: { root: "Normal", ascending: "Normal" },
      masses: { clotVegMass: "Absent" },
      finalImpression: "Large Pericardial Effusion (approx. 22mm posterior, 18mm anterior, 15mm lateral). No overt signs of chamber collapse (tamponade) on current evaluation, but diastolic right ventricular collapse should be monitored. Dilated IVC with poor collapse. Normal biventricular systolic function.",
      advice: "Urgent clinical and echocardiographic monitoring. Consider therapeutic pericardiocentesis if clinically indicated.",
    },
  },
};
